var questions = [
    { "question": 'What does JS stand for', 
    "option1": 'Javascript',
    "option2": 'Just Sauce',
    "option3": 'Jerry Springer',
    "option4": 'Justice Served', 
    "answer": "1" },
    { "question": 'What version of HTML is commonly used?', 
    "option1": '3',
    "option2": '4',
    "option3": '5',
    "option4": '12',
    "answer": "3" },
    { "question": 'What is used to set something into local storage?', 
    "option1": '.getItem',
    "option2": '.setItem',
    "option3": '.betItem',
    "option4": '.tetItem',
    "answer": "2" },
    { "question": 'What program does the class use to set our Git repos?', 
    "option1": 'bash',
    "option2": 'crash',
    "option3": 'stash',
    "option4": 'mash',
    "answer": "1" },
    { "question": 'How many questions in this quiz so far?', 
    "option1": '2',
    "option2": '3',
    "option3": '5',
    "option4": 'C',
    "answer": "3" }
  ];